### ISSUE TITLE
can not set class name in {% render_field %}

### ISSUE THREAD

**Issue by pyshawon** [simhnna/django-widgets-improved#2]
Hello,
i'm trying to use custom class name but it not work. it work other page in same application. 

{% render_field form.planned_cycle class="form-control" %}

Error :+1: 
      old_as_widget = field.as_widget
      AttributeError: 'str' object has no attribute 'as_widget

**Comment by simhnna** [comment]
Sorry, the github notification somehow got lost in my inbox...
This error was due to django-widget-tweaks not being compatible with django > 2.0

This repo should not be affected. Can you double check that you are actually using django-widgets-improved? A quick `pip freeze` should show you what's being used

**Comment by mrksays** [comment]
I have the same issue I am using 
astroid==2.1.0
colorama==0.4.1
cython==0.29.3
Django==2.1.4
django-widget-tweaks==1.4.3
gender-guesser==0.4.0
gunicorn==19.9.0
html5lib==1.0.1
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
mysqlclient==1.3.14
pdfkit==0.6.1
Pillow==5.4.0
pylint==2.2.2
PyPDF2==1.26.0
pytesseract==0.2.6
pytz==2018.7
reportlab==3.5.13
six==1.12.0
typed-ast==1.2.0
webencodings==0.5.1
wkhtmltopdf==0.2
wrapt==1.11.1
xhtml2pdf==0.2.3

**Comment by simhnna** [comment]
You are not using django-widgets-improved. 

Uninstall django-widget-tweaks and then install django-widgets-improved

**Comment by mrksays** [comment]
@simhnna thanks
